name: Add new rewarder

permissions:
  contents: write

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Added new rewarder config to rewarderConfigs.json
          file_pattern: rewarderConfigs.json
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Propose new rewarder
        env:
          SAFE_SIGNER_MNEMONIC: ${{ secrets.SAFE_SIGNER_MNEMONIC }}
          AURORA_API_KEY: ${{ secrets.AURORA_API_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: |
          yarn
          yarn hardhat run scripts/ops/safeDeployRewarder.ts --network aurora
